name: table_calendar
description: Specific calendar made for matchPro. Fork from Aleksander Woźniak
version: 1.0.1
author: Guillaume Colas, fork from Aleksander Woźniak
homepage: https://github.com/Athlas/table_calendar_matchpro.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^2.5.3
  flutter:
    sdk: flutter

  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
